version: '3.4'

services:
  firstservice:
    container_name: diceroll
    image: firstservice
    build:
      context: microservices/First_Service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - grafanaa
    ports:
      - 8080:8080

  secondservice:
    container_name: diceroll2
    image: secondservice
    build:
      context: microservices/Second_Service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - grafanaa
    ports:
      - 8081:8081

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./Devops/otel/otel-collector.yaml:/otel-local-config.yaml
    depends_on:
      - tempo
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./Devops/tempo/tempo.yaml:/etc/tempo.yaml
      - ./Devops/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # tempo http
      - "9095:9095" # tempo grpc
      - "4317" # otlp grpc
      - "4318" # otlp http
  grafanaa:
    image: grafana/grafana:9.4.3
    volumes:
      - ./Devops/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"